import {useEffect,useState} from 'react';import {Link} from 'react-router-dom';import Header from '../components/Header';import Footer from '../components/Footer';import ProductCard from '../components/ProductCard';import {api} from '../lib/api';
export default function Home(){const[data,setData]=useState<any>();const[err,setErr]=useState('');useEffect(()=>{api<any>('/home').then(setData).catch(e=>setErr(e.message))},[]);if(err)return <><Header/><main className="section container"><div className="notice error">{err}</div></main><Footer/></>;if(!data)return <><Header/><main className="section container">Loading…</main></>;const by=(k:string)=>data.sections.find((s:any)=>s.section_key===k);return <><Header/>{data.sections.map((s:any)=><Section key={s.id} s={s} data={data} by={by}/>) }<Footer/></>}
function Section({s,data,by}:{s:any,data:any,by:(k:string)=>any}){const c=s.content||{};switch(s.section_key){case'hero':return <section className="hero" style={c.imageUrl?{backgroundImage:`linear-gradient(90deg,rgba(8,8,9,.85),rgba(8,8,9,.28)),url(${c.imageUrl})`}:{}}><div className="container hero-inner"><div className="eyebrow">{c.eyebrow||'TREND WEAR BD'}</div><h1>{c.title||s.title}</h1><p>{c.description||s.description}</p><div className="actions"><Link className="btn btn-red" to={c.ctaLink||'/shop'}>{c.ctaText||'Shop Collection'}</Link>{c.secondaryText&&<Link className="btn btn-light" to={c.secondaryLink||'/shop'}>{c.secondaryText}</Link>}</div></div></section>;
case'categories':return <section id="categories" className="section"><div className="container"><Head s={s} action="View all"/><div className="grid categories">{data.categories.slice(0,8).map((x:any)=><Link className="cat" key={x.id} to={`/shop?category=${x.slug}`}>{x.image_url&&<img src={x.image_url} alt={x.name}/>}<span>{x.name}</span></Link>)}</div></div></section>;
case'products':return <section className="section"><div className="container"><Head s={s} action="Shop all"/><div className="grid grid-4">{data.products.slice(0,12).map((p:any)=><ProductCard key={p.id} p={p}/>)}</div></div></section>;
case'banner':return data.banners[0]&&<section className="section"><div className="container"><div className="banner" style={data.banners[0].image_url?{backgroundImage:`linear-gradient(90deg,rgba(0,0,0,.78),rgba(0,0,0,.15)),url(${data.banners[0].image_url})`}:{}}><div><div className="eyebrow">Trend Wear BD</div><h2 className="serif" style={{fontSize:48,margin:'12px 0'}}>{data.banners[0].heading}</h2><p>{data.banners[0].description}</p>{data.banners[0].button_text&&<Link className="btn btn-red" to={data.banners[0].button_action||'/shop'}>{data.banners[0].button_text}</Link>}</div></div></div></section>;
case'services':return <section className="section"><div className="container"><Head s={s}/><div className="grid grid-3">{data.services.length?data.services.map((x:any)=><div className="card" style={{padding:24}} key={x.id}><div className="eyebrow">{x.title}</div><h3>{x.description}</h3>{x.button_text&&<Link className="btn btn-light" to={x.button_action||'/shop'}>{x.button_text}</Link>}</div>):(c.items||[]).map((x:any,i:number)=><div className="card" style={{padding:24}} key={i}><div style={{fontSize:28}}>{x.icon||'✦'}</div><h3>{x.title}</h3><p className="muted">{x.description}</p></div>)}</div></div></section>;
case'why':return <section className="section"><div className="container"><Head s={s}/><div className="grid grid-3">{(c.features||[]).map((f:any,i:number)=><div className="card" style={{padding:24}} key={i}><div style={{fontSize:28}}>{f.icon||'✦'}</div><h3>{f.title}</h3><p className="muted">{f.description}</p></div>)}</div></div></section>;
case'reviews':return <section id="reviews" className="section"><div className="container"><Head s={s}/>{data.reviews.length?<div className="review-wrap"><div className="review-track">{[...data.reviews,...data.reviews].map((r:any,i:number)=><article className="card review" key={`${r.id}-${i}`}>{r.image_url&&<img src={r.image_url} alt={`Review by ${r.customer_name}`}/>}<div className="stars">{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</div><p>“{r.review_text}”</p><strong>{r.customer_name}</strong></article>)}</div></div>:<div className="notice">Customer reviews will appear here after approval.</div>}</div></section>;
case'faq':return <section className="section"><div className="container"><Head s={s}/><div className="grid">{(c.items||[]).map((x:any,i:number)=><details className="card" style={{padding:20}} key={i}><summary><strong>{x.question}</strong></summary><p className="muted">{x.answer}</p></details>)}</div></div></section>;
case'about':return <section className="section"><div className="container"><Head s={s}/><div className="card" style={{padding:28}}><p>{data.settings.aboutText||s.description}</p></div></div></section>;
case'contact':return <section id="contact" className="section"><div className="container"><div className="banner"><div><div className="eyebrow">Need help?</div><h2 className="serif" style={{fontSize:48,margin:'12px 0'}}>{s.title}</h2><p>{s.description}</p>{data.settings.whatsapp&&<a className="btn btn-red" href={`https://wa.me/${String(data.settings.whatsapp).replace(/\D/g,'')}`} target="_blank" rel="noreferrer">WhatsApp us</a>}</div></div></div></section>;
default:return null}}
function Head({s,action}:{s:any,action?:string}){const image=s.content?.imageUrl;return <><div className="section-head"><div><div className="eyebrow">Trend Wear BD</div><h2>{s.title}</h2>{s.description&&<p className="muted">{s.description}</p>}</div>{action&&<Link className="btn btn-light" to="/shop">{action}</Link>}</div>{image&&<div className="section-picture"><img src={image} alt={s.title||'Trend Wear BD'} loading="lazy"/></div>}</>}
