import {useEffect,useState} from 'react';import {Link,useLocation,useNavigate} from 'react-router-dom';import {api,upload} from '../lib/api';
const nav=[['/admin','Dashboard'],['/admin/products','Products'],['/admin/categories','Categories'],['/admin/orders','Orders'],['/admin/landing','Landing Page'],['/admin/banners','Banners'],['/admin/services','Services'],['/admin/reviews','Reviews'],['/admin/leads','Leads'],['/admin/social','Social'],['/admin/settings','Settings']];
export default function AdminApp(){const loc=useLocation(),navg=useNavigate();const[me,setMe]=useState<any>();useEffect(()=>{api('/auth/me').then(setMe).catch(()=>navg('/admin/login'))},[]);if(!me)return <div style={{padding:30}}>Loading admin…</div>;return <div className="admin-layout"><aside className="admin-side"><Link to="/admin" style={{fontWeight:900,fontSize:18,marginBottom:20,display:'block'}}>Trend Wear BD</Link>{nav.map(([p,l])=><Link className={loc.pathname===p?'active':''} key={p} to={p}>{l}</Link>)}<button className="btn btn-light" style={{width:'100%',marginTop:25}} onClick={async()=>{await api('/auth/logout',{method:'POST'});navg('/admin/login')}}>Logout</button></aside><main className="admin-main"><RoutesContent path={loc.pathname}/></main></div>}
function Head({title,sub}:{title:string,sub?:string}){return <div className="admin-header"><div><div className="eyebrow">Admin control</div><h1 style={{margin:'5px 0'}}>{title}</h1>{sub&&<p className="muted">{sub}</p>}</div></div>}
function RoutesContent({path}:{path:string}){if(path==='/admin')return <Dashboard/>;if(path==='/admin/products')return <Products/>;if(path==='/admin/categories')return <Categories/>;if(path==='/admin/orders')return <Orders/>;if(path==='/admin/landing')return <Landing/>;if(path==='/admin/banners')return <Crud type="banners" title="Banners" fields={['heading','description','button_text','button_action','image_url','sort_order']}/>;if(path==='/admin/services')return <Crud type="services" title="Services" fields={['title','description','button_text','button_action','image_url','price','sort_order']}/>;if(path==='/admin/reviews')return <Reviews/>;if(path==='/admin/leads')return <Leads/>;if(path==='/admin/social')return <Social/>;return <Settings/>}
function Dashboard(){const[d,setD]=useState<any>();useEffect(()=>{api('/admin/dashboard').then(setD)},[]);return <><Head title="Dashboard" sub="Live store overview"/>{d&&<><div className="stat-grid">{[['Orders',d.orders],['Pending',d.pending],['Revenue',`৳${Number(d.revenue||0).toLocaleString()}`],['Products',d.products]].map(x=><div className="stat" key={x[0]}>{x[0]}<strong>{x[1]}</strong></div>)}</div><section className="section" style={{paddingTop:30}}><h3>Recent orders</h3><div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th></tr></thead><tbody>{d.recent.map((o:any)=><tr key={o.id}><td>{o.order_number}</td><td>{o.customer_name}</td><td>৳{Number(o.total).toLocaleString()}</td><td>{o.status}</td></tr>)}</tbody></table></div></section></>}</>}
function Products(){const[items,setItems]=useState<any[]>([]),[cats,setCats]=useState<any[]>([]),[editing,setEditing]=useState<any>(null),[file,setFile]=useState<File>();const load=()=>Promise.all([api<any>('/admin/products'),api<any>('/categories')]).then(([p,c])=>{setItems(p.items);setCats(c.items)});useEffect(()=>{load()},[]);async function save(e:any){e.preventDefault();const f=new FormData(e.currentTarget),body:any=Object.fromEntries(f.entries());if(file)body.images=JSON.stringify([(await upload(file)).url]);else body.images=JSON.stringify(editing?.images||[]);await api(editing?`/admin/products/${editing.id}`:'/admin/products',{method:editing?'PUT':'POST',body:JSON.stringify(body)});setEditing(null);setFile(undefined);load()}return <><Head title="Products" sub="Manage catalog, pricing, stock and images"/><div className="grid grid-2"><form className="card" style={{padding:20}} onSubmit={save}><h3>{editing?'Edit':'Add'} product</h3>{['name','slug','description','price','sale_price','stock','sku','sort_order'].map(k=><div className="field" key={k}><label>{k}</label><input name={k} defaultValue={editing?.[k]??''} required={['name','price','stock'].includes(k)}/></div>)}<div className="field"><label>Category</label><select name="category_id" defaultValue={editing?.category_id||''}><option value="">None</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><label><input type="checkbox" name="featured" defaultChecked={!!editing?.featured}/> Featured</label><label><input type="checkbox" name="active" defaultChecked={editing?.active!==false}/> Active</label><div className="field"><label>Image</label><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>setFile(e.target.files?.[0])}/></div><button className="btn btn-red">Save</button>{editing&&<button type="button" className="btn btn-light" onClick={()=>setEditing(null)}>Cancel</button>}</form><div className="table-wrap"><table><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th></th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td>{p.name}</td><td>৳{Number(p.sale_price??p.price).toLocaleString()}</td><td>{p.stock}</td><td><button onClick={()=>setEditing(p)}>Edit</button> <button onClick={async()=>{if(confirm('Delete this product?')){await api(`/admin/products/${p.id}`,{method:'DELETE'});load()}}}>Delete</button></td></tr>)}</tbody></table></div></div></>}
function Categories(){const[items,setItems]=useState<any[]>([]),[edit,setEdit]=useState<any>(null);const load=()=>api<any>('/admin/categories').then(x=>setItems(x.items));useEffect(()=>{load()},[]);async function save(e:any){e.preventDefault();const b:any=Object.fromEntries(new FormData(e.currentTarget).entries());b.active=b.active==='on';await api(edit?`/admin/categories/${edit.id}`:'/admin/categories',{method:edit?'PUT':'POST',body:JSON.stringify(b)});setEdit(null);load()}return <><Head title="Categories"/><div className="grid grid-2"><form className="card" style={{padding:20}} onSubmit={save}><h3>{edit?'Edit':'Add'} category</h3>{['name','slug','image_url','sort_order'].map(k=><div className="field" key={k}><label>{k}</label><input name={k} defaultValue={edit?.[k]||''}/></div>)}<label><input name="active" type="checkbox" defaultChecked={edit?.active!==false}/> Active</label><button className="btn btn-red">Save</button></form><div className="table-wrap"><table><thead><tr><th>Name</th><th>Slug</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.slug}</td><td><button onClick={()=>setEdit(x)}>Edit</button> <button onClick={async()=>{if(confirm('Delete category?')){await api(`/admin/categories/${x.id}`,{method:'DELETE'});load()}}}>Delete</button></td></tr>)}</tbody></table></div></div></>}
function Orders(){const[items,setItems]=useState<any[]>([]);const load=()=>api<any>('/admin/orders').then(x=>setItems(x.items));useEffect(()=>{load()},[]);return <><Head title="Orders"/><div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Phone</th><th>Total</th><th>Status</th><th>Payment</th></tr></thead><tbody>{items.map(o=><tr key={o.id}><td>{o.order_number}</td><td>{o.customer_name}</td><td>{o.phone}</td><td>৳{Number(o.total).toLocaleString()}</td><td><select value={o.status} onChange={async e=>{await api(`/admin/orders/${o.id}`,{method:'PATCH',body:JSON.stringify({status:e.target.value})});load()}}>{['pending','confirmed','processing','shipped','delivered','cancelled'].map(s=><option key={s}>{s}</option>)}</select></td><td>{o.payment_method} / {o.payment_status}</td></tr>)}</tbody></table></div></>}
function Landing(){
 const[items,setItems]=useState<any[]>([]),[open,setOpen]=useState<string|null>(null),[saving,setSaving]=useState(false);
 const load=()=>api<any>('/admin/landing').then(x=>setItems(x.items||[]));
 useEffect(()=>{load()},[]);
 async function save(s:any){setSaving(true);try{await api(`/admin/landing/${s.section_key}`,{method:'PUT',body:JSON.stringify(s)});await load();}finally{setSaving(false)}}
 async function move(i:number,d:number){const a=[...items],j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];setItems(a);for(let n=0;n<a.length;n++)await api(`/admin/landing/${a[n].section_key}`,{method:'PUT',body:JSON.stringify({...a[n],sort_order:n})});}
 return <><Head title="Landing Page Builder" sub="Edit homepage content, pictures, visibility and section order. Changes publish immediately."/><div className="landing-toolbar"><div className="notice">All homepage sections are database-driven. Use <b>Save & Publish</b> to update the live website.</div><Link className="btn btn-light" to="/" target="_blank">Preview website</Link></div>{items.map((s,i)=><div className={`card landing-row ${!s.enabled?'is-hidden':''}`} key={s.id}><div className="landing-row-head"><div><span className="section-chip">{i+1}</span><div className="landing-meta"><strong>{s.section_key}</strong><h3>{s.title||'Untitled section'}</h3><span className="muted">{s.enabled?'Visible on website':'Hidden from website'}</span></div></div><div className="landing-actions"><button disabled={i===0} onClick={()=>move(i,-1)} aria-label="Move section up">↑</button><button disabled={i===items.length-1} onClick={()=>move(i,1)} aria-label="Move section down">↓</button><button className="btn btn-light" onClick={()=>setOpen(open===s.id?null:s.id)}>{open===s.id?'Close editor':'Edit section'}</button></div></div>{open===s.id&&<SectionEditor section={s} onSave={save} saving={saving}/>}</div>)}</>
}

function Field({label,children,hint}:{label:string,children:any,hint?:string}){return <div className="field"><label>{label}</label>{children}{hint&&<small className="muted">{hint}</small>}</div>}
function SectionEditor({section,onSave,saving}:{section:any,onSave:(x:any)=>Promise<void>,saving:boolean}){
 const[s,setS]=useState<any>({...section,content:section.content||{}}),[file,setFile]=useState<File>(),[error,setError]=useState('');
 const c=s.content||{};
 const set=(k:string,v:any)=>setS((x:any)=>({...x,[k]:v}));
 const setC=(k:string,v:any)=>setS((x:any)=>({...x,content:{...(x.content||{}),[k]:v}}));
 const uploadImage=async()=>{if(!file)return c.imageUrl||'';const r=await upload(file);return r.url};
 const save=async()=>{setError('');try{const imageUrl=await uploadImage();const content={...c,...(imageUrl?{imageUrl}:{})};await onSave({...s,content});setFile(undefined);}catch(e:any){setError(e.message||'Could not save changes.')}};
 const renderList=(key:string,fields:string[],title:string)=>{const list=Array.isArray(c[key])?c[key]:[];return <div className="editor-list"><div className="editor-list-head"><strong>{title}</strong><button type="button" className="btn btn-light" onClick={()=>setC(key,[...list,Object.fromEntries(fields.map(f=>[f,'']))])}>+ Add</button></div>{list.map((item:any,i:number)=><div className="editor-item" key={i}><div className="editor-item-title">{title} {i+1}<button type="button" onClick={()=>setC(key,list.filter((_:any,n:number)=>n!==i))}>Remove</button></div>{fields.map(f=><Field key={f} label={f}><textarea rows={f==='description'||f==='answer'||f==='review_text'?3:2} value={item[f]||''} onChange={e=>{const a=[...list];a[i]={...a[i],[f]:e.target.value};setC(key,a)}}/></Field>)}</div>)}</div>};
 return <div className="landing-editor">
  <div className="grid grid-2">
   <Field label="Section title"><input value={s.title||''} onChange={e=>set('title',e.target.value)}/></Field>
   <Field label="Section description"><textarea rows={3} value={s.description||''} onChange={e=>set('description',e.target.value)}/></Field>
  </div>
  {section.section_key==='hero'&&<>
   <div className="grid grid-2"><Field label="Eyebrow"><input value={c.eyebrow||''} onChange={e=>setC('eyebrow',e.target.value)}/></Field><Field label="Hero heading"><input value={c.title||''} onChange={e=>setC('title',e.target.value)}/></Field></div>
   <Field label="Hero description"><textarea rows={4} value={c.description||''} onChange={e=>setC('description',e.target.value)}/></Field>
   <div className="grid grid-2"><Field label="Primary button text"><input value={c.ctaText||''} onChange={e=>setC('ctaText',e.target.value)}/></Field><Field label="Primary button link"><input value={c.ctaLink||'/shop'} onChange={e=>setC('ctaLink',e.target.value)}/></Field><Field label="Secondary button text"><input value={c.secondaryText||''} onChange={e=>setC('secondaryText',e.target.value)}/></Field><Field label="Secondary button link"><input value={c.secondaryLink||'/shop'} onChange={e=>setC('secondaryLink',e.target.value)}/></Field></div>
  </>}
  {section.section_key==='faq'&&renderList('items',['question','answer'],'FAQ')}
  {(section.section_key==='why'||section.section_key==='services')&&renderList(section.section_key==='why'?'features':'items',['title','description'],'Feature')}
  <div className="grid grid-2">
   <Field label="Section picture" hint="JPG, PNG, WebP or GIF. Maximum 5MB. No SVG."><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>setFile(e.target.files?.[0])}/>{(file||c.imageUrl)&&<div className="image-preview">{file?<span>{file.name}</span>:<img src={c.imageUrl} alt="Current section"/>}</div>}</Field>
   <Field label="Picture URL (optional)" hint="Use a public JPG/PNG/WebP image URL, or upload a picture above."><input value={c.imageUrl||''} onChange={e=>setC('imageUrl',e.target.value)}/></Field>
  </div>
  <label className="toggle"><input type="checkbox" checked={!!s.enabled} onChange={e=>set('enabled',e.target.checked)}/><span>Show this section on the website</span></label>
  {error&&<div className="notice error">{error}</div>}
  <div className="editor-footer"><button className="btn btn-red" type="button" disabled={saving} onClick={save}>{saving?'Saving…':'Save & Publish'}</button><button className="btn btn-light" type="button" onClick={()=>setS({...section,content:section.content||{}})}>Reset</button></div>
 </div>
}
function Crud({type,title,fields}:{type:'banners'|'services',title:string,fields:string[]}){const[items,setItems]=useState<any[]>([]),[edit,setEdit]=useState<any>(null),[file,setFile]=useState<File>();const load=()=>api<any>(`/admin/${type}`).then(x=>setItems(x.items));useEffect(()=>{load()},[]);async function save(e:any){e.preventDefault();const b:any=Object.fromEntries(new FormData(e.currentTarget).entries());b.active=b.active==='on';if(file)b.image_url=(await upload(file)).url;await api(edit?`/admin/${type}/${edit.id}`:`/admin/${type}`,{method:edit?'PUT':'POST',body:JSON.stringify(b)});setEdit(null);setFile(undefined);load()}return <><Head title={title}/><div className="grid grid-2"><form className="card" style={{padding:20}} onSubmit={save}><h3>{edit?'Edit':'Add'} {title.slice(0,-1)}</h3>{fields.map(k=><div className="field" key={k}><label>{k}</label><input name={k} defaultValue={edit?.[k]??''}/></div>)}<input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0])}/><label><input name="active" type="checkbox" defaultChecked={edit?.active!==false}/> Active</label><button className="btn btn-red">Save</button></form><div className="grid">{items.map(x=><div className="card" style={{padding:18}} key={x.id}><strong>{x.heading||x.title}</strong><p className="muted">{x.description}</p><button onClick={()=>setEdit(x)}>Edit</button> <button onClick={async()=>{if(confirm('Delete?')){await api(`/admin/${type}/${x.id}`,{method:'DELETE'});load()}}}>Delete</button></div>)}</div></div></>}
function Reviews(){const[items,setItems]=useState<any[]>([]),[edit,setEdit]=useState<any>(null),[file,setFile]=useState<File>();const load=()=>api<any>('/admin/reviews').then(x=>setItems(x.items));useEffect(()=>{load()},[]);async function save(e:any){e.preventDefault();const b:any=Object.fromEntries(new FormData(e.currentTarget).entries());b.rating=Number(b.rating);b.active=b.active==='on';if(file)b.image_url=(await upload(file)).url;await api(edit?`/admin/reviews/${edit.id}`:'/admin/reviews',{method:edit?'PUT':'POST',body:JSON.stringify(b)});setEdit(null);setFile(undefined);load()}return <><Head title="Customer Reviews" sub="Upload customer photos and control the horizontal auto-scroll review strip."/><div className="grid grid-2"><form className="card" style={{padding:20}} onSubmit={save}><h3>{edit?'Edit':'Add'} review</h3><div className="form"><input name="customer_name" placeholder="Customer name" defaultValue={edit?.customer_name||''} required/><select name="rating" defaultValue={edit?.rating||5}>{[5,4,3,2,1].map(x=><option key={x}>{x}</option>)}</select><textarea name="review_text" placeholder="Review" defaultValue={edit?.review_text||''} required/><input name="sort_order" type="number" defaultValue={edit?.sort_order||0}/><label><input name="active" type="checkbox" defaultChecked={edit?.active!==false}/> Visible</label><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0])}/><button className="btn btn-red">Save</button></div></form><div className="grid">{items.map(r=><div className="card" style={{padding:18}} key={r.id}><strong>{r.customer_name}</strong><div className="stars">{'★'.repeat(r.rating)}</div><p>{r.review_text}</p><button onClick={()=>setEdit(r)}>Edit</button> <button onClick={async()=>{if(confirm('Delete review?')){await api(`/admin/reviews/${r.id}`,{method:'DELETE'});load()}}}>Delete</button></div>)}</div></div></>}
function Leads(){const[items,setItems]=useState<any[]>([]);const load=()=>api<any>('/admin/leads').then(x=>setItems(x.items));useEffect(()=>{load()},[]);return <><Head title="Leads"/><div className="table-wrap"><table><thead><tr><th>Name</th><th>Contact</th><th>Message</th><th>Status</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.phone||x.email||''}</td><td>{x.message}</td><td><select value={x.status} onChange={async e=>{await api(`/admin/leads/${x.id}`,{method:'PATCH',body:JSON.stringify({status:e.target.value})});load()}}>{['new','contacted','closed'].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div></>}
function Social(){const[items,setItems]=useState<any[]>([]);const load=()=>api<any>('/admin/social').then(x=>setItems(x.items));useEffect(()=>{load()},[]);return <><Head title="Social Links"/><div className="grid">{items.map(x=><div className="card" style={{padding:18}} key={x.id}><div className="field"><label>{x.platform}</label><input value={x.url} onChange={e=>setItems(items.map(y=>y.id===x.id?{...y,url:e.target.value}:y))}/></div><label><input type="checkbox" checked={!!x.enabled} onChange={e=>setItems(items.map(y=>y.id===x.id?{...y,enabled:e.target.checked}:y))}/> Enabled</label><button className="btn btn-light" onClick={async()=>{await api(`/admin/social/${x.id}`,{method:'PUT',body:JSON.stringify(x)})}}>Save</button></div>)}</div></>}
function Settings(){const[s,setS]=useState<any>({});useEffect(()=>{api<any>('/admin/settings').then(x=>setS(x.settings||{}))},[]);const keys=['websiteName','aboutText','phone','email','whatsapp','address','businessHours','deliveryCharge','bkashNumber','nagadNumber','bankName','bankAccountName','bankAccountNumber','bankInstructions','copyright'];return <><Head title="Store Settings" sub="Contact, delivery and payment instructions shown throughout the website."/><div className="card" style={{padding:22}}><div className="form">{keys.map(k=><div className="field" key={k}><label>{k}</label>{k==='aboutText'||k==='bankInstructions'?<textarea rows={4} value={s[k]||''} onChange={e=>setS({...s,[k]:e.target.value})}/>:<input value={s[k]||''} onChange={e=>setS({...s,[k]:e.target.value})}/>}</div>)}<button className="btn btn-red" onClick={async()=>{await api('/admin/settings',{method:'PUT',body:JSON.stringify(s)});alert('Settings saved')}}>Save settings</button></div></div></>}
