import 'dotenv/config';
import express from 'express';
import cookieParser from 'cookie-parser';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { createClient, type Client } from '@libsql/client';
import { randomUUID } from 'crypto';
import { S3Client, PutObjectCommand, DeleteObjectCommand } from '@aws-sdk/client-s3';
import multer from 'multer';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { z } from 'zod';

const __dirname=path.dirname(fileURLToPath(import.meta.url)); const ROOT=path.resolve(__dirname,'../..'); const app=express();
const db=createClient({url:process.env.TURSO_DATABASE_URL||'',authToken:process.env.TURSO_AUTH_TOKEN});
const uploadMiddleware=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024},fileFilter:(_r,f,cb)=>cb(null,/^image\/(jpeg|png|webp|gif)$/i.test(f.mimetype))});
const r2=process.env.R2_ENDPOINT&&process.env.R2_ACCESS_KEY_ID&&process.env.R2_SECRET_ACCESS_KEY&&process.env.R2_BUCKET?new S3Client({endpoint:process.env.R2_ENDPOINT,region:'auto',credentials:{accessKeyId:process.env.R2_ACCESS_KEY_ID,secretAccessKey:process.env.R2_SECRET_ACCESS_KEY}}):null;
const secret=process.env.AUTH_SECRET||''; if(!secret) console.warn('AUTH_SECRET is missing.');
app.use(express.json({limit:'2mb'})); app.use(cookieParser()); app.use(rateLimit({windowMs:60000,limit:120,standardHeaders:'draft-8',legacyHeaders:false}));
async function q<T=any>(sql:string,args:any[]=[]):Promise<T[]>{const r=await db.execute({sql,args}); return r.rows as unknown as T[];}
async function run(sql:string,args:any[]=[]){return db.execute({sql,args});}
const j=(v:any)=>typeof v==='string'?JSON.parse(v||'{}'):v; const bool=(v:any)=>v===true||v===1||v==='1'||v==='on'||v==='true';
function normalize(row:any){if(!row)return row; for(const k of ['content','images','variants','details','value','variant']) if(row[k]!=null&&typeof row[k]==='string'){try{row[k]=JSON.parse(row[k])}catch{}} return row;}
async function init(){if(!process.env.TURSO_DATABASE_URL)throw new Error('TURSO_DATABASE_URL is missing'); const sql=fs.readFileSync(path.join(ROOT,'db/schema.sql'),'utf8'); for(const statement of sql.split(';').map(x=>x.trim()).filter(Boolean)) await run(statement); await seed();}
async function seed(){const settings:any={websiteName:'Trend Wear BD',aboutText:'Premium fashion for everyone.',phone:'',email:'',whatsapp:'',address:'',businessHours:'',deliveryCharge:'0',copyright:'© Trend Wear BD. All rights reserved.',bkashNumber:'',nagadNumber:'',bankInstructions:'',bankName:'',bankAccountName:'',bankAccountNumber:'',facebook:'',instagram:'',tiktok:'',youtube:''}; for(const [k,v] of Object.entries(settings))await run('INSERT OR IGNORE INTO site_settings(key,value) VALUES(?,?)',[k,JSON.stringify(v)]);
 const sections:any[]=[['hero','The new standard of everyday style','A premium fashion destination for men, women and kids.',{eyebrow:'TREND WEAR BD',title:'Wear your confidence.',description:'Curated fashion for every mood, moment and generation.',ctaText:'Shop Collection',ctaLink:'/shop',secondaryText:'Explore',secondaryLink:'/shop',imageUrl:'/logo.jpg'}],['categories','Shop by category','Find the fit for your world.',{}],['products','Featured collection','Handpicked pieces from Trend Wear BD.',{}],['banner','Seasonal edit','Make a statement with the latest collection.',{}],['services','Our promise','Everything you need for a smooth fashion experience.',{items:[{title:'Fast delivery',description:'Reliable delivery across Bangladesh.',icon:'✦'},{title:'Easy exchange',description:'Simple support when you need it.',icon:'↻'},{title:'Secure checkout',description:'Safe and transparent ordering.',icon:'✓'}]}],['why','Why choose Trend Wear BD','Quality, variety and service built around you.',{features:[{icon:'✦',title:'Quality first',description:'Thoughtfully selected fashion.'},{icon:'◈',title:'For everyone',description:'Styles across men, women and kids.'},{icon:'✓',title:'Easy ordering',description:'Simple checkout and reliable support.'}]}],['reviews','Customer reviews','Real customer feedback appears here after admin approval.',{}],['faq','Frequently asked questions','Quick answers for shoppers.',{items:[{question:'How can I order?',answer:'Add products to cart and complete checkout.'},{question:'What payment methods are available?',answer:'Cash on delivery, bKash, Nagad and bank transfer.'}]}],['about','About Trend Wear BD','',{}],['contact','Let’s talk.','Reach our team for orders and support.',{}],['footer','Trend Wear BD','',{}]];
 for(let i=0;i<sections.length;i++){const [key,title,desc,content]=sections[i];await run('INSERT OR IGNORE INTO landing_sections(id,section_key,title,description,content,enabled,sort_order) VALUES(?,?,?,?,?,1,?)',[randomUUID(),key,title,desc,JSON.stringify(content),i]);}
 const socials=[['Facebook',''],['Instagram',''],['TikTok',''],['WhatsApp',''],['YouTube','']]; for(let i=0;i<socials.length;i++)await run('INSERT OR IGNORE INTO social_links(id,platform,url,enabled,sort_order) VALUES(?,?,?,1,?)',[randomUUID(),socials[i][0],socials[i][1],i]);}
function sign(id:string){return jwt.sign({sub:id},secret,{expiresIn:'7d'});} function requireAdmin(req:any,res:any,next:any){try{const t=req.cookies.admin_token;if(!t)throw 0;const p:any=jwt.verify(t,secret);req.adminId=p.sub;next()}catch{res.status(401).json({error:'Unauthorized'})}}
const authLimit=rateLimit({windowMs:600000,limit:10});
app.get('/api/health',async(_r,res)=>res.json({ok:true,database:'turso'}));
app.post('/api/auth/login',authLimit,async(req,res)=>{const s=z.object({email:z.string().email(),password:z.string().min(8)}).safeParse(req.body);if(!s.success)return res.status(400).json({error:'Invalid login data'});const rows=await q<any>('SELECT * FROM admin_users WHERE lower(email)=lower(?)',[s.data.email]);if(!rows[0]||!(await bcrypt.compare(s.data.password,rows[0].password_hash)))return res.status(401).json({error:'Invalid email or password'});res.cookie('admin_token',sign(rows[0].id),{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:604800000});res.json({ok:true});});
app.post('/api/auth/logout',(_r,res)=>{res.clearCookie('admin_token');res.json({ok:true})}); app.get('/api/auth/me',requireAdmin,async(req:any,res)=>{const r=await q<any>('SELECT id,email,name FROM admin_users WHERE id=?',[req.adminId]);if(!r[0])return res.status(401).json({error:'Unauthorized'});res.json(r[0])});
app.get('/api/site',async(_r,res)=>{const rows=await q<any>('SELECT key,value FROM site_settings');const settings:any={};rows.forEach(x=>settings[x.key]=j(x.value));res.json({settings})});
app.get('/api/social',async(_r,res)=>res.json({items:(await q('SELECT * FROM social_links ORDER BY sort_order')).map(normalize)}));
app.get('/api/categories',async(_r,res)=>res.json({items:await q('SELECT * FROM categories WHERE active=1 ORDER BY sort_order,name')}));
app.get('/api/home',async(_r,res)=>{const sections=(await q<any>('SELECT * FROM landing_sections WHERE enabled=1 ORDER BY sort_order')).map(normalize);const products=(await q<any>(`SELECT p.*,c.name category_name,c.slug category_slug FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.active=1 ORDER BY p.featured DESC,p.sort_order,p.created_at DESC LIMIT 12`)).map(normalize);const categories=await q('SELECT * FROM categories WHERE active=1 ORDER BY sort_order,name');const reviews=await q('SELECT * FROM reviews WHERE active=1 ORDER BY sort_order,created_at DESC');const banners=await q('SELECT * FROM banners WHERE active=1 ORDER BY sort_order');const services=await q('SELECT * FROM services WHERE active=1 ORDER BY sort_order');const site=await q<any>('SELECT key,value FROM site_settings');const settings:any={};site.forEach(x=>settings[x.key]=j(x.value));res.json({sections,products,categories,reviews,banners,services,settings});});
app.get('/api/products',async(req,res)=>{const qv=String(req.query.q||''),cat=String(req.query.category||''),sort=String(req.query.sort||'new');let order='p.created_at DESC';if(sort==='price_asc')order='COALESCE(p.sale_price,p.price) ASC';if(sort==='price_desc')order='COALESCE(p.sale_price,p.price) DESC';if(sort==='featured')order='p.featured DESC,p.created_at DESC';const rows=await q<any>(`SELECT p.*,c.name category_name,c.slug category_slug FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.active=1 AND (?='' OR lower(p.name) LIKE '%'||lower(?)||'%' OR lower(p.description) LIKE '%'||lower(?)||'%') AND (?='' OR c.slug=?) ORDER BY ${order}`,[qv,qv,qv,cat,cat]);res.json({items:rows.map(normalize),categories:await q('SELECT * FROM categories WHERE active=1 ORDER BY sort_order,name')});});
app.get('/api/products/:slug',async(req,res)=>{const r=await q<any>('SELECT p.*,c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.slug=? AND p.active=1',[req.params.slug]);if(!r[0])return res.status(404).json({error:'Product not found'});res.json(normalize(r[0]));});
app.post('/api/leads',async(req,res)=>{const s=z.object({name:z.string().min(2),phone:z.string().optional(),email:z.string().email().optional().or(z.literal('')),message:z.string().min(3),interest:z.string().optional()}).safeParse(req.body);if(!s.success)return res.status(400).json({error:'Please complete the contact form.'});await run('INSERT INTO leads(id,name,phone,email,message,interest) VALUES(?,?,?,?,?,?)',[randomUUID(),s.data.name,s.data.phone||null,s.data.email||null,s.data.message,s.data.interest||null]);res.json({ok:true});});
app.post('/api/orders',async(req,res)=>{const schema=z.object({name:z.string().min(2),phone:z.string().min(6),email:z.string().email().optional().or(z.literal('')),address:z.string().min(5),city:z.string().optional(),notes:z.string().optional(),payment_method:z.enum(['cod','bkash','nagad','bank_transfer']),payment_transaction_id:z.string().optional(),payment_sender_number:z.string().optional(),items:z.array(z.object({productId:z.string().uuid(),quantity:z.number().int().positive(),variant:z.record(z.string(),z.string()).optional()})).min(1)});const p=schema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Please check your checkout information.'});const d=p.data;const tx=await db.transaction('write');try{const lines:any[]=[];let subtotal=0;for(const item of d.items){const r=await tx.execute({sql:'SELECT * FROM products WHERE id=? AND active=1',args:[item.productId]});const prod:any=r.rows[0];if(!prod)throw new Error('A product is unavailable.');if(Number(prod.stock)<item.quantity)throw new Error(`${prod.name} does not have enough stock.`);const price=Number(prod.sale_price??prod.price);subtotal+=price*item.quantity;lines.push({prod,item,price});}const sr=await tx.execute({sql:'SELECT value FROM site_settings WHERE key=?',args:['deliveryCharge']});const delivery=Number(sr.rows[0]?j(sr.rows[0].value):0)||0;const total=subtotal+delivery;const customerId=randomUUID(),orderId=randomUUID(),orderNumber=`TWB-${Date.now().toString(36).toUpperCase()}-${Math.floor(100+Math.random()*900)}`;await tx.execute({sql:'INSERT INTO customers(id,name,phone,email,address,city) VALUES(?,?,?,?,?,?)',args:[customerId,d.name,d.phone,d.email||null,d.address,d.city||null]});await tx.execute({sql:'INSERT INTO orders(id,order_number,customer_id,customer_name,phone,email,address,city,notes,payment_method,payment_transaction_id,payment_sender_number,subtotal,delivery_charge,total) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',args:[orderId,orderNumber,customerId,d.name,d.phone,d.email||null,d.address,d.city||null,d.notes||null,d.payment_method,d.payment_transaction_id||null,d.payment_sender_number||null,subtotal,delivery,total]});for(const l of lines){await tx.execute({sql:'INSERT INTO order_items(id,order_id,product_id,product_name,sku,quantity,unit_price,variant) VALUES(?,?,?,?,?,?,?,?)',args:[randomUUID(),orderId,l.prod.id,l.prod.name,l.prod.sku,l.item.quantity,l.price,JSON.stringify(l.item.variant||{})]});await tx.execute({sql:'UPDATE products SET stock=stock-?,updated_at=CURRENT_TIMESTAMP WHERE id=?',args:[l.item.quantity,l.prod.id]});}await tx.execute({sql:'INSERT INTO payments(id,order_id,method,transaction_id,sender_number,amount) VALUES(?,?,?,?,?,?)',args:[randomUUID(),orderId,d.payment_method,d.payment_transaction_id||null,d.payment_sender_number||null,total]});await tx.commit();res.json({ok:true,order_number:orderNumber,total});}catch(e:any){await tx.rollback();res.status(400).json({error:e.message||'Order could not be created.'});}});
app.get('/api/admin/dashboard',requireAdmin,async(_r,res)=>{const [a,b,c,d,recent]=await Promise.all([q<any>('SELECT count(*) n FROM orders'),q<any>(`SELECT count(*) n FROM orders WHERE status='pending'`),q<any>(`SELECT COALESCE(sum(total),0) n FROM orders WHERE status!='cancelled'`),q<any>('SELECT count(*) n FROM products'),q('SELECT id,order_number,customer_name,total,status FROM orders ORDER BY created_at DESC LIMIT 10')]);res.json({orders:Number(a[0].n),pending:Number(b[0].n),revenue:Number(c[0].n),products:Number(d[0].n),recent});});
async function deleteR2Url(url?:string){if(!r2||!url||!process.env.R2_PUBLIC_BASE_URL||!process.env.R2_BUCKET)return;const base=process.env.R2_PUBLIC_BASE_URL.replace(/\/$/,'')+'/';if(!url.startsWith(base))return;try{await r2.send(new DeleteObjectCommand({Bucket:process.env.R2_BUCKET,Key:url.slice(base.length)}))}catch{}}
app.get('/api/admin/products',requireAdmin,async(_r,res)=>res.json({items:(await q<any>('SELECT * FROM products ORDER BY created_at DESC')).map(normalize)}));
app.post('/api/admin/products',requireAdmin,async(req,res)=>{const b=req.body,id=randomUUID(),slug=(b.slug||b.name).toString().toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');await run('INSERT INTO products(id,name,slug,description,price,sale_price,category_id,stock,sku,featured,active,images,sort_order) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,b.name,slug,b.description||'',Number(b.price),b.sale_price?Number(b.sale_price):null,b.category_id||null,Number(b.stock),b.sku||null,bool(b.featured)?1:0,b.active===false||b.active==='false'?0:1,JSON.stringify(j(b.images||'[]')),Number(b.sort_order||0)]);res.json({ok:true,id})});
app.put('/api/admin/products/:id',requireAdmin,async(req,res)=>{const b=req.body,old=await q<any>('SELECT images FROM products WHERE id=?',[req.params.id]);const images=j(b.images||'[]');await run('UPDATE products SET name=?,description=?,price=?,sale_price=?,category_id=?,stock=?,sku=?,featured=?,active=?,images=?,sort_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[b.name,b.description||'',Number(b.price),b.sale_price?Number(b.sale_price):null,b.category_id||null,Number(b.stock),b.sku||null,bool(b.featured)?1:0,bool(b.active)?1:0,JSON.stringify(images),Number(b.sort_order||0),req.params.id]);const oldImgs=j(old[0]?.images||'[]');for(const u of oldImgs)if(!images.includes(u))await deleteR2Url(u);res.json({ok:true})});
app.delete('/api/admin/products/:id',requireAdmin,async(req,res)=>{const old=await q<any>('SELECT images FROM products WHERE id=?',[req.params.id]);await run('DELETE FROM products WHERE id=?',[req.params.id]);for(const u of j(old[0]?.images||'[]'))await deleteR2Url(u);res.json({ok:true})});
app.get('/api/admin/categories',requireAdmin,async(_r,res)=>res.json({items:await q('SELECT * FROM categories ORDER BY sort_order,name')}));
app.post('/api/admin/categories',requireAdmin,async(req,res)=>{const b=req.body;const slug=(b.slug||b.name).toString().toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');await run('INSERT INTO categories(id,name,slug,image_url,active,sort_order) VALUES(?,?,?,?,?,?)',[randomUUID(),b.name,slug,b.image_url||null,bool(b.active)?1:0,Number(b.sort_order||0)]);res.json({ok:true})});
app.put('/api/admin/categories/:id',requireAdmin,async(req,res)=>{const b=req.body;await run('UPDATE categories SET name=?,slug=?,image_url=?,active=?,sort_order=? WHERE id=?',[b.name,b.slug,b.image_url||null,bool(b.active)?1:0,Number(b.sort_order||0),req.params.id]);res.json({ok:true})});
app.delete('/api/admin/categories/:id',requireAdmin,async(req,res)=>{await run('DELETE FROM categories WHERE id=?',[req.params.id]);res.json({ok:true})});
app.get('/api/admin/orders',requireAdmin,async(_r,res)=>res.json({items:await q('SELECT * FROM orders ORDER BY created_at DESC')}));
app.get('/api/admin/orders/:id',requireAdmin,async(req,res)=>{const o=await q<any>('SELECT * FROM orders WHERE id=?',[req.params.id]);if(!o[0])return res.status(404).json({error:'Order not found'});res.json({order:o[0],items:await q('SELECT * FROM order_items WHERE order_id=?',[req.params.id]),payment:(await q('SELECT * FROM payments WHERE order_id=? ORDER BY created_at DESC',[req.params.id]))[0]||null})});
app.patch('/api/admin/orders/:id',requireAdmin,async(req,res)=>{const statuses=['pending','confirmed','processing','shipped','delivered','cancelled'];if(!statuses.includes(req.body.status))return res.status(400).json({error:'Invalid status'});await run('UPDATE orders SET status=?,payment_status=CASE WHEN ? IN (\'cod\') THEN payment_status ELSE payment_status END,updated_at=CURRENT_TIMESTAMP WHERE id=?',[req.body.status,req.body.status,req.params.id]);res.json({ok:true})});
app.get('/api/admin/landing',requireAdmin,async(_r,res)=>res.json({items:(await q<any>('SELECT * FROM landing_sections ORDER BY sort_order')).map(normalize)}));
app.put('/api/admin/landing/:key',requireAdmin,async(req,res)=>{const b=req.body;const old=await q<any>('SELECT content FROM landing_sections WHERE section_key=?',[req.params.key]);if(!old[0])return res.status(404).json({error:'Landing section not found'});const oldContent=j(old[0].content||'{}');const content=b.content||{};await run('UPDATE landing_sections SET title=?,description=?,content=?,enabled=?,sort_order=?,updated_at=CURRENT_TIMESTAMP WHERE section_key=?',[b.title||'',b.description||'',JSON.stringify(content),bool(b.enabled)?1:0,Number(b.sort_order||0),req.params.key]);if(oldContent.imageUrl&&oldContent.imageUrl!==content.imageUrl)await deleteR2Url(oldContent.imageUrl);res.json({ok:true})});
app.get('/api/admin/banners',requireAdmin,async(_r,res)=>res.json({items:await q('SELECT * FROM banners ORDER BY sort_order')}));
app.post('/api/admin/banners',requireAdmin,async(req,res)=>{const b=req.body;await run('INSERT INTO banners(id,heading,description,image_url,button_text,button_action,active,sort_order) VALUES(?,?,?,?,?,?,?,?)',[randomUUID(),b.heading,b.description||'',b.image_url||null,b.button_text||null,b.button_action||null,bool(b.active)?1:0,Number(b.sort_order||0)]);res.json({ok:true})});
app.put('/api/admin/banners/:id',requireAdmin,async(req,res)=>{const b=req.body;await run('UPDATE banners SET heading=?,description=?,image_url=?,button_text=?,button_action=?,active=?,sort_order=? WHERE id=?',[b.heading,b.description||'',b.image_url||null,b.button_text||null,b.button_action||null,bool(b.active)?1:0,Number(b.sort_order||0),req.params.id]);res.json({ok:true})});
app.delete('/api/admin/banners/:id',requireAdmin,async(req,res)=>{await run('DELETE FROM banners WHERE id=?',[req.params.id]);res.json({ok:true})});
app.get('/api/admin/services',requireAdmin,async(_r,res)=>res.json({items:await q('SELECT * FROM services ORDER BY sort_order')}));
app.post('/api/admin/services',requireAdmin,async(req,res)=>{const b=req.body;await run('INSERT INTO services(id,title,description,image_url,price,button_text,button_action,active,sort_order) VALUES(?,?,?,?,?,?,?,?,?)',[randomUUID(),b.title,b.description||'',b.image_url||null,b.price?Number(b.price):null,b.button_text||null,b.button_action||null,bool(b.active)?1:0,Number(b.sort_order||0)]);res.json({ok:true})});
app.put('/api/admin/services/:id',requireAdmin,async(req,res)=>{const b=req.body;await run('UPDATE services SET title=?,description=?,image_url=?,price=?,button_text=?,button_action=?,active=?,sort_order=? WHERE id=?',[b.title,b.description||'',b.image_url||null,b.price?Number(b.price):null,b.button_text||null,b.button_action||null,bool(b.active)?1:0,Number(b.sort_order||0),req.params.id]);res.json({ok:true})});
app.delete('/api/admin/services/:id',requireAdmin,async(req,res)=>{await run('DELETE FROM services WHERE id=?',[req.params.id]);res.json({ok:true})});
app.get('/api/admin/reviews',requireAdmin,async(_r,res)=>res.json({items:await q('SELECT * FROM reviews ORDER BY sort_order,created_at DESC')}));
app.post('/api/admin/reviews',requireAdmin,async(req,res)=>{const b=req.body;await run('INSERT INTO reviews(id,customer_name,rating,review_text,image_url,active,sort_order) VALUES(?,?,?,?,?,?,?)',[randomUUID(),b.customer_name,Number(b.rating),b.review_text,b.image_url||null,bool(b.active)?1:0,Number(b.sort_order||0)]);res.json({ok:true})});
app.put('/api/admin/reviews/:id',requireAdmin,async(req,res)=>{const b=req.body;await run('UPDATE reviews SET customer_name=?,rating=?,review_text=?,image_url=COALESCE(?,image_url),active=?,sort_order=? WHERE id=?',[b.customer_name,Number(b.rating),b.review_text,b.image_url||null,bool(b.active)?1:0,Number(b.sort_order||0),req.params.id]);res.json({ok:true})});
app.delete('/api/admin/reviews/:id',requireAdmin,async(req,res)=>{const old=await q<any>('SELECT image_url FROM reviews WHERE id=?',[req.params.id]);await run('DELETE FROM reviews WHERE id=?',[req.params.id]);await deleteR2Url(old[0]?.image_url);res.json({ok:true})});
app.get('/api/admin/leads',requireAdmin,async(_r,res)=>res.json({items:await q('SELECT * FROM leads ORDER BY created_at DESC')})); app.patch('/api/admin/leads/:id',requireAdmin,async(req,res)=>{if(!['new','contacted','closed'].includes(req.body.status))return res.status(400).json({error:'Invalid status'});await run('UPDATE leads SET status=? WHERE id=?',[req.body.status,req.params.id]);res.json({ok:true})});
app.get('/api/admin/settings',requireAdmin,async(_r,res)=>{const rows=await q<any>('SELECT key,value FROM site_settings');const settings:any={};rows.forEach(x=>settings[x.key]=j(x.value));res.json({settings})}); app.put('/api/admin/settings',requireAdmin,async(req,res)=>{for(const [k,v] of Object.entries(req.body))await run('INSERT INTO site_settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP',[k,JSON.stringify(v)]);res.json({ok:true})});
app.get('/api/admin/social',requireAdmin,async(_r,res)=>res.json({items:await q('SELECT * FROM social_links ORDER BY sort_order')})); app.put('/api/admin/social/:id',requireAdmin,async(req,res)=>{const b=req.body;await run('UPDATE social_links SET platform=?,url=?,enabled=?,sort_order=? WHERE id=?',[b.platform,b.url||'',bool(b.enabled)?1:0,Number(b.sort_order||0),req.params.id]);res.json({ok:true})});
app.post('/api/uploads',requireAdmin,uploadMiddleware.single('file'),async(req:any,res)=>{try{if(!r2||!process.env.R2_BUCKET||!process.env.R2_PUBLIC_BASE_URL)return res.status(503).json({error:'Image storage is not configured.'});if(!req.file)return res.status(400).json({error:'Please select a valid image, max 5MB.'});const ext:any={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif'};const key=`uploads/${randomUUID()}.${ext[req.file.mimetype]}`;await r2.send(new PutObjectCommand({Bucket:process.env.R2_BUCKET,Key:key,Body:req.file.buffer,ContentType:req.file.mimetype,CacheControl:'public,max-age=31536000,immutable'}));res.json({ok:true,url:`${process.env.R2_PUBLIC_BASE_URL!.replace(/\/$/,'')}/${key}`,key});}catch{res.status(500).json({error:'Image upload failed.'})}});
const clientDist=path.join(ROOT,'dist/client');if(fs.existsSync(clientDist)){app.use(express.static(clientDist));app.use((req,res,next)=>{if(req.path.startsWith('/api/'))return res.status(404).json({error:'Not found'});res.sendFile(path.join(clientDist,'index.html'))});}
const port=Number(process.env.PORT||10000);init().then(()=>app.listen(port,'0.0.0.0',()=>console.log(`Trend Wear BD running on ${port}`))).catch(e=>{console.error(e);process.exit(1)});
